import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#004f54',
        'on-primary': '#ffffff',
        'primary-container': '#01696f',
        'on-primary-container': '#97e6ec',
        'primary-fixed': '#a1f0f6',
        'primary-fixed-dim': '#85d3da',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f54',
        secondary: '#555f70',
        'on-secondary': '#ffffff',
        'secondary-container': '#d6e0f4',
        'on-secondary-container': '#596374',
        'secondary-fixed': '#d9e3f7',
        'secondary-fixed-dim': '#bdc7db',
        'on-secondary-fixed': '#121c2a',
        'on-secondary-fixed-variant': '#3d4757',
        tertiary: '#6e3815',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#8b4f2a',
        'on-tertiary-container': '#ffceb5',
        'tertiary-fixed': '#ffdbc9',
        'tertiary-fixed-dim': '#ffb68d',
        'on-tertiary-fixed': '#331200',
        'on-tertiary-fixed-variant': '#6e3815',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#f7fafa',
        'on-surface': '#181c1d',
        'surface-dim': '#d7dbda',
        'surface-bright': '#f7fafa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f4f4',
        'surface-container': '#ebeeee',
        'surface-container-high': '#e6e9e9',
        'surface-container-highest': '#e0e3e3',
        'on-surface-variant': '#3f4949',
        'surface-variant': '#e0e3e3',
        outline: '#6f797a',
        'outline-variant': '#bec8c9',
        background: '#f7fafa',
        'on-background': '#181c1d',
        'inverse-surface': '#2d3131',
        'inverse-on-surface': '#eef1f1',
        'inverse-primary': '#85d3da',
        'surface-tint': '#01696f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'container-margin': '24px',
        gutter: '16px',
      },
      fontSize: {
        display: ['30px', { lineHeight: '38px', fontWeight: '700', letterSpacing: '-0.02em' }],
        h1: ['24px', { lineHeight: '32px', fontWeight: '600', letterSpacing: '-0.01em' }],
        h2: ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      fontFamily: {
        'google-sans': ['"Google Sans"', 'Roboto', 'sans-serif'],
        roboto: ['Roboto', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'elevation-1': '0px 1px 2px rgba(0,0,0,0.3), 0px 1px 3px 1px rgba(0,0,0,0.15)',
        'elevation-2': '0px 1px 2px rgba(0,0,0,0.3), 0px 2px 6px 2px rgba(0,0,0,0.15)',
        'elevation-3': '0px 4px 8px 3px rgba(0,0,0,0.15), 0px 1px 3px rgba(0,0,0,0.3)',
      },
    },
  },
  plugins: [],
}

export default config
